### ISSUE TITLE
Type error in nodejs 10.x

### ISSUE THREAD

**Issue by cm-vinoth** [nikunjdnp/serverless-ami-creation-deletion#2]
Hi Nikunj,
Thanks for the excellent article. I am completely new to node js. 
I am getting the below error in lambda execution.
Response:
{
  "errorType": "TypeError",
  "errorMessage": "CreateListFromArrayLike called on non-object",
  "trace": [
    "TypeError: CreateListFromArrayLike called on non-object",
    "    at async.waterfall.params.Filters.Name (/var/task/index.js:112:35)",
    "    at nextTask (/var/task/node_modules/async/dist/async.js:5324:14)",
    "    at next (/var/task/node_modules/async/dist/async.js:5331:9)",
    "    at /var/task/node_modules/async/dist/async.js:969:16",
    "    at /var/task/index.js:99:17",
    "    at nextTask (/var/task/node_modules/async/dist/async.js:5324:14)",
    "    at next (/var/task/node_modules/async/dist/async.js:5331:9)",
    "    at /var/task/node_modules/async/dist/async.js:969:16",
    "    at Response.<anonymous> (/var/task/index.js:64:21)",
    "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)"
  ]
}

Regards,
Vinoth

**Comment by nikunjdnp** [comment]
Hi @cm-vinoth, please make sure that ec2 instances are in `running` or `stopped` state. One more, all the ec2 instances have a tag `backupNode` : `true`.

**Comment by cm-vinoth** [comment]
Hi @nikunjdnp ,
Thanks for the info. It works now. But deletion part is not working properly
```
 var ExpireTimestamp = imageName.replace(/_/g, " ").split(" ");
var currentTimestamp = moment.tz(new Date(), "Asia/Kolkata").valueOf();
if (ExpireTimestamp[2] < currentTimestamp) 
```
say this AMI 'AMI_i-0c787016e5bf17dc5_1569806135477' created 2 days back and i kept retention period as 2 days but still it does not get deleted so far.
Can you suggest me what is wrong here?

**Comment by raj-yadav9** [comment]
@cm-vinoth  I am getting same error as your first one . I have  tags added but the error still persists

**Comment by nikunjdnp** [comment]
Hi @raj-yadav9 @cm-vinoth, I will look into it. Please give me some time. 

In the meantime, if you have any idea about how to reproduce it, please share here. 

Thanks,
Nikunj

**Comment by raj-yadav9** [comment]
@nikunjdnp My error is resolved thanks. Some how environment variables was not getting properly. Setting it manually in code worked.

**Comment by vinodkumar4b9** [comment]
Hi @nikunjdnp @cm-vinoth @raj-yadav9 

Can some one who was able to fix the error can help me with this issue

I guess code is not working as expected, I have done each and everything as you said ,now I am getting a error saying as below
{
"errorType": "TypeError",
"errorMessage": "CreateListFromArrayLike called on non-object",
"code": "TypeError",
"message": "CreateListFromArrayLike called on non-object",
"time": "2020-10-14T10:41:00.436Z",
"stack": [
"TypeError: CreateListFromArrayLike called on non-object",
" at async.waterfall.params.Filters.Name (/var/task/index.js:112:35)",
" at nextTask (/var/task/node_modules/async/dist/async.js:5324:14)",
" at next (/var/task/node_modules/async/dist/async.js:5331:9)",
" at /var/task/node_modules/async/dist/async.js:969:16",
" at /var/task/index.js:99:17",
" at nextTask (/var/task/node_modules/async/dist/async.js:5324:14)",
" at next (/var/task/node_modules/async/dist/async.js:5331:9)",
" at /var/task/node_modules/async/dist/async.js:969:16",
" at Response.<anonymous> (/var/task/index.js:64:21)",
" at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:369:18)"
]
}

**Comment by raj-yadav9** [comment]
@vinodkumar4b9 Try adding print statements before each block. Looks like instance is not getting selected

**Comment by nikunjdnp** [comment]
Hi @vinodkumar4b9, Let me know if you're still facing the error.
